use crate::evaluator::Request;
use crate::plan::IssuancePlan;
use crate::policy::PolicyFile;
use serde::Serialize;
use std::fs;
use std::path::Path;

#[derive(Debug, Serialize)]
struct CompiledPolicy<'a> {
    version: u32,
    ca_name: &'a str,
    default_ttl: &'a str,
    max_ttl: &'a str,
    rule_count: usize,
    resources: Vec<CompiledResource<'a>>,
}

#[derive(Debug, Serialize)]
struct CompiledResource<'a> {
    id: &'a str,
    host: &'a str,
    trusted_ca_path: &'a str,
}

pub fn write_compile_artifacts(
    policy: &PolicyFile,
    out: &Path,
) -> Result<(), Box<dyn std::error::Error>> {
    fs::create_dir_all(out.join("ca"))?;
    fs::create_dir_all(out.join("sshd"))?;
    fs::create_dir_all(out.join("policy"))?;

    fs::write(
        out.join("ca/accessc_ca.pub"),
        "# accessc MVP placeholder\n# Replace this file with your OpenSSH CA public key.\n",
    )?;
    let trusted_ca_path = policy
        .resources
        .first()
        .map(|resource| resource.trusted_ca_path.as_str())
        .unwrap_or("/etc/ssh/accessc_ca.pub");
    fs::write(
        out.join("sshd/trusted-user-ca-keys.conf"),
        format!("{trusted_ca_path}\n"),
    )?;
    fs::write(
        out.join("sshd/sshd_config.snippet"),
        format!("# Generated by accessc\nTrustedUserCAKeys {trusted_ca_path}\n"),
    )?;

    let compiled = CompiledPolicy {
        version: policy.version,
        ca_name: &policy.ca.name,
        default_ttl: &policy.ca.default_ttl,
        max_ttl: &policy.ca.max_ttl,
        rule_count: policy.rules.len(),
        resources: policy
            .resources
            .iter()
            .map(|resource| CompiledResource {
                id: &resource.id,
                host: &resource.host,
                trusted_ca_path: &resource.trusted_ca_path,
            })
            .collect(),
    };
    fs::write(
        out.join("policy/compiled-policy.json"),
        serde_json::to_string_pretty(&compiled)?,
    )?;
    fs::write(
        out.join("README.next-steps.md"),
        "# accessc next steps\n\nThe MVP compiles OpenSSH artifacts and plans certificate issuance. It does not sign certificates or manage private CA keys.\n",
    )?;
    Ok(())
}

pub fn write_plan_artifacts(
    _policy: &PolicyFile,
    _request: &Request,
    plan: &IssuancePlan,
    out: &Path,
) -> Result<(), Box<dyn std::error::Error>> {
    fs::create_dir_all(out.join("ssh"))?;
    fs::create_dir_all(out.join("audit"))?;
    fs::create_dir_all(out.join("plans"))?;

    fs::write(
        out.join("ssh/config.snippet"),
        format!(
            "# Generated by accessc\nHost {}\n  HostName {}\n  CertificateFile ~/.ssh/{}-cert.pub\n",
            plan.host, plan.host, plan.plan_id
        ),
    )?;
    fs::write(
        out.join("ssh/issue-command.txt"),
        format!("{}\n", plan.issue_command),
    )?;
    fs::write(
        out.join(format!("plans/{}-plan.json", plan.plan_id)),
        serde_json::to_string_pretty(plan)?,
    )?;
    fs::write(
        out.join(format!(
            "audit/{}-{}-receipt.json",
            plan.created_at_unix, plan.plan_id
        )),
        serde_json::to_string_pretty(&plan.audit_receipt())?,
    )?;
    Ok(())
}
